### ISSUE TITLE
Configuration name too short in database for evaluations

### ISSUE THREAD

**Issue by Kyle-Herceg** [US-EPA-CAMD/PI-1#5878]
Run the following configuration through the evaluation process.

QueryFailedError: value too long for type character varying(100)
    at QueryFailedError.TypeORMError [as constructor] (/home/subrataroy/EPA_CAMD/easey-camd-services/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/home/subrataroy/EPA_CAMD/easey-camd-services/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/home/subrataroy/EPA_CAMD/easey-camd-services/src/driver/postgres/PostgresQueryRunner.ts:263:19)
    at step (/home/subrataroy/EPA_CAMD/easey-camd-services/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/home/subrataroy/EPA_CAMD/easey-camd-services/node_modules/tslib/tslib.js:176:57)
    at rejected (/home/subrataroy/EPA_CAMD/easey-camd-services/node_modules/tslib/tslib.js:167:69)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  query: 'INSERT INTO "camdecmpsaux"."evaluation_set"("evaluation_set_id", "mon_plan_id", "submitted_on", "user_id", "user_email", "fac_id", "oris_code", "fac_name", "configuration") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)',
  parameters: [
    'a97da632-35bf-45f4-a848-9d4e5eeca683',
    'MDC-33188EC8E0A74F2480927C4CD59B45AE',
    2023-10-28T11:36:28.007Z,
    'subrataroy',
    'subrataroy@cvpcorp.com',
    488,
    2494,
    'Gowanus Generating Station',
    'CT01-1, CT01-2, CT01-3, CT01-4, CT01-5, CT01-6, CT01-7, CT01-8, CT02-1, CT02-2, CT02-3, CT02-4, CT02-5, CT02-6, CT02-7, CT02-8, CT03-1, CT03-2, CT03-3, CT03-4, CT03-5, CT03-6, CT03-7, CT03-8, CT04-1, CT04-2, CT04-3, CT04-4, CT04-5, CT04-6, CT04-7, CT04-8, CP0001'
  ],
  driverError: error: value too long for type character varying(100)
      at /home/subrataroy/EPA_CAMD/easey-camd-services/node_modules/pg/lib/client.js:526:17
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    length: 99,
    severity: 'ERROR',
    code: '22001',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'varchar.c',
    line: '636',
    routine: 'varchar'
  },
  length: 99,
  severity: 'ERROR',
  code: '22001',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'varchar.c',
  line: '636',
  routine: 'varchar'
}

**Comment by JanellC** [comment]
Internal databse changed has been completed
